[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = [
  "npm ci",
  "mkdir -p ./bin",
  "chmod +x ./bin/yt-dlp",
  "echo '---- FILE TYPE ----'",
  "file ./bin/yt-dlp",
  "echo '---- FIRST 5 LINES ----'",
  "head -n 5 ./bin/yt-dlp"
]
