[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = [
  "npm ci",
  "mkdir -p ./bin",
"curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux -o ./bin/yt-dlp",  "chmod +x ./bin/yt-dlp",
  "./bin/yt-dlp --version"
]